apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-validator-api-blue
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ci-validator-api
      version: blue

  template:
    metadata:
      labels:
        app: ci-validator-api
        version: blue
    spec:
      containers:
      - name: ci-validator-api-container
        image: ci-validator-api:1.0.0
        ports:
        - containerPort: 8000