apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-validator-api-green
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ci-validator-api
      version: green

  template:
    metadata:
      labels:
        app: ci-validator-api
        version: green
    spec:
      containers:
      - name: ci-validator-api-container
        image: ci-validator-api:2.0.0
        ports:
        - containerPort: 8000